version: '3.8'

services:
  #nginx:
  #container_name: nginx
  #volumes:
  #   -             "./:/var/www/html"
  #build:  
  #  context:      requirements/nginx
  #  dockerfile:   Dockerfile
  # ports:
  #   -             "443:443"
  # restart:        on-failure
  
  mariadb:
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "./requirements/mariadb/tool:/home"
      - "~/anloisea/data:/var/lib/mysql"
    build:
      context: . 
      dockerfile: ./requirements/mariadb/Dockerfile
    env_file: .env
    environment:
      DB_NAME: inception
