version: '3.9'

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    env_file: .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        CERTS_:  ${CERTS_}
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/anloisea/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/anloisea/data/wordpress
      o: bind

networks:
  inception:
    name: inception
    driver: bridge
