version: '3.9'

services:
  nginx:
    container_name: nginx
    volumes:
      - "wordpress:/var/www/html"
    build:  
      context:      requirements/nginx
      dockerfile:   Dockerfile
    ports:
     -  "443:443"
    env_file: .env
    restart: always
  
      #mariadb:
      # container_name: mariadb
      #build: requirements/mariadb/.
      # volumes:
      #- "mariadb:/var/lib/mysql"
      # env_file: 
      # - .env
      #networks:
      #- inception
      #restart: always

volumes:
  database:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/${USER}/anloisea/data/database'
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/${USER}/anloisea/data/wordpress'

networks:
  inception:
    name: inception
