version: '3.9'

services: 
  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - "mariadb:/var/lib/mysql"
    env_file: .env
    networks:
      - inception
    restart: always
    ports:
      - "3306:3306"

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - "wordpress:/var/www/html"
    env_file: .env
    networks:
      - inception
    restart: always
    ports:
      - "9000:9000"

  nginx:
    container_name: nginx
    volumes:
      - "wordpress:/var/www/html"
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        CERTS_: ${CERTS_}
    ports:
     -  "443:443"
    depends_on: 
      - wordpress
    env_file: .env
    networks:
      - inception
    restart: always
  
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/anloisea/data/mariadb'
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/anloisea/data/wordpress'

networks:
  inception:
    name: inception
    driver: bridge
